name: App CI
on:
  pull_request:
  
  push:
    branches:
      - master
      
concurrency:
  group: ${{ github.ref }}-ci
  
jobs:
  release:
    if: ${{ github.ref == 'refs/heads/master' }}
    env:
      DOCKER_IMAGE: 558860702682.dkr.ecr.us-east-1.amazonaws.com/toptal/app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses : actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get latest tag
        run: git checkout ${{ github.ref }} && echo "LATEST_TAG=$(git describe --tags --abbrev=0 | cut -c2-)" >> $GITHUB_ENV
      - name: Print LATEST_TAG
        run: echo ${{ env.LATEST_TAG }}
      
          
